services:
  home-controller-hub-postgres:
    container_name: home-controller-hub-postgres
    image: postgres:18
    environment:
      - POSTGRES_PASSWORD=home-controller-hubp@ss
      - POSTGRES_USER=user_home-controller-hub
      - POSTGRES_DB=db_home-controller-hub
    ports:
      - 15432:5432
    volumes:
      - pg_data:/var/lib/postgresql
    networks:
      - home-controller-hub-network

  home-controller-hub-rabbitmq:
    container_name: home-controller-hub-rabbitmq
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-guest}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - home-controller-hub-network

  homecontrollerhub-mosquitto:
      image: eclipse-mosquitto:2
      container_name: homecontrollerhub-mosquitto
      restart: unless-stopped
      ports:
        - "1883:1883"
        - "9001:9001"
      volumes:
        - ./mosquitto/config:/mosquitto/config
        - ./mosquitto/data:/mosquitto/data
        - ./mosquitto/log:/mosquitto/log

  # home-controller-hub-redis:
  #   container_name: home-controller-hub-redis
  #   image: redis:latest
  #   command: ["redis-server", "--requirepass", "local-dev-redis-password", "--bind", "0.0.0.0"]
  #   ports:
  #     - "6480:6379"
  #   networks:
  #     - home-controller-hub-network

  # home-controller-hub-api:
  #   container_name: home-controller-hub-api
  #   depends_on:
  #     # - home-controller-hub-redis
  #     - home-controller-hub-postgres
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "6001:80"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Testing
  #   networks:
  #     - home-controller-hub-network

networks:
  home-controller-hub-network:
    external: true

volumes:
  pg_data:
  rabbitmq_data:
